config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :users, :controllers => { :registrations => 'registrations' }
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  mount_uploader :picture, PictureUploader
  validate :picture_size

  private

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  attr_accessor :card_number, :card_cvv, :card_expires_month, :card_expires_year
  belongs_to :user

  def self.month_options
    Date::MONTHNAMES.compact.each_with_index.map { |name, i| ["#{i+1} - #{name}", i+1] }
  end

  def self.year_options
    (Date.today.year..(Date.today.year+10)).to_a
  end

  def process_payment
    customer = Stripe::Customer.create(email: email, card: token)

    Stripe::Charge.create(customer: customer.id,
                          amount: 1000,
                          description: 'Premium',
                          currency: 'usd')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  has_one :payment
  accepts_nested_attributes_for :payment
  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    @image.user = current_user
    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:name, :picture, :user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def create
    build_resource(sign_up_params)
    resource.class.transaction do
      resource.save
      yield resource if block_given?
      if resource.persisted?
        @payment = Payment.new({ email: params["user"]["email"],
                                 token: params[:payment]["token"], user_id: resource.id })
        flash[:error] = "Please check registration errors" unless @payment.valid?

        begin
          @payment.process_payment
          @payment.save
        rescue Exception => e
          flash[:error] = e.message
          resource.destroy
          puts 'Payment Failed'
          render :new and return
        end
        if resource.active_for_authentication?
          set_flash_message! :notice, :signed_up
          sign_up(resource_name, resource)
          respond_with resource, location: after_sign_up_path_for(resource)
        else
          set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
          expire_data_after_sign_in!
          respond_with resource, location: after_inactive_sign_up_path_for(resource)
        end
      else
        clean_up_passwords resource
        set_minimum_password_length
        respond_with resource
      end
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:payment)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/images/_form.html.erb
<%= form_with(model: image, local: true, multipart: true, class: "form-horizontal image") do |form| %>
  <% if image.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <h4 class="alert-heading">The following errors prevented this image from being saved</h4>
      <ul>
        <% image.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :picture %>
    <%= form.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %>
  </div>

  <div class="form-group justify-content-md-center">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

<script type="text/javascript">
  $('#image_picture').bind('change', function() {
      var size_in_megabytes = this.files[0].size/1024/1024;
      if (size_in_megabytes > 5) {
          alert('Maximum file size is 5MB');
      }

  });
</script>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Images</h1>

<table class="table table-hover">
  <thead>
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Picture</th>
    <th scope="col">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @images.each do |image| %>
    <tr>
      <td><%= link_to image.name, image %></td>
      <td><%= image_tag(image.picture.url, size: "100x100") %></td>
      <td>
        <%= link_to 'Edit', edit_image_path(image), class: "btn btn-sm btn-outline-info" %>
        <%= link_to 'Delete', image, method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-sm btn-outline-danger" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @image.name %>
</p>

<p>
  <%= image_tag(@image.picture.url, size: "300x300") if @image.picture? %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-info text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Martin Margonari", "https://github.com/martinmargonari", class: "text-white" %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Photo App", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Link 1", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Link 2", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
            <a class="dropdown-item" href="#">Add action here</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Add other action here</a>
          </div>
        </li>
        <li class='nav-item'>
          <%= link_to("Logout", destroy_user_session_path,
                      class: "btn btn-outline-warning logout-button", method: :delete)%>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>PhotoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <div class="container">
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/welcome/index.html.erb
<% if current_user %>
  <h3>Welcome: <%= current_user.email %></h3>
<% else %>
  <div class="jumbotron">
    <h2>Welcome to the Photo Management App!</h2>
    <p class="lead">
      You'll love managing your Photos with our application. Sign up!
    </p>
  </div>

  <div class="row justify-content-md-center">
    <div class="col-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header">
          <h4>Premium Plan</h4>
        </div>
        <div class="card-title">
          Price $10
        </div>
        <div class="card-body d-flex flex-column">
          <ul class="text-justify">
            <li>Unlimited Image Uploads</li>
            <li>Responsive design</li>
            <li>Access anywhere</li>
          </ul>
          <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary sign-up mt-auto' %>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card text-center shadow mb-5 bg-white rounded h-200">
        <div class="card-header">
          <h4>Amaze Plan</h4>
        </div>
        <div class="card-title">
          Price $20
        </div>
        <div class="card-body d-flex flex-column">
          <ul class="text-justify">
            <li>Unlimited Image Uploads</li>
            <li>Responsive design</li>
            <li>Access anywhere</li>
            <li class='extra'>Unlimited projects</li>
          </ul>
          <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary sign-up mt-auto' %>
        </div>
      </div>
    </div>
  </div>
<% end %>